name: metano_runtime
description: A runtime library for Metano-compiled Dart/Flutter applications.
version: 0.2.0
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
